{
 "title": "K8s / Storage / Heketi",
 "description": "Dashboard of data exported from Heketi via Prometheus Service as deployed by OpenShift Container Storage (OCS) 3.x.",
 "tags": [
  "openshift",
  "k8s",
  "storage",
  "heketi"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_OPENSHIFT_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Heketi Cluster Job", "query": "label_values(heketi_up,job)" }
  ]
 },
 "panels": [
  { "title": "All Heketis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heketi Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "targets": [
    { "expr": "heketi_up" }
   ]
  },
  {
   "title": "Available Capacity in a Week Based on Daily Use Rate",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "(sum by (job,cluster) (predict_linear(heketi_device_free_bytes [1d], 7 * 24 * 60 * 60) ))"
    }
   ]
  },
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 } },
  {
   "title": "Available Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Free Space" }
   ],
   "targets": [
    {
     "expr": "(\n  (sum by (job,cluster) (heketi_device_free_bytes))\n)",
     "legendFormat": "{{job}} ({{cluster}})"
    }
   ]
  },
  {
   "title": "Available Capacity in a Week Based on Daily Use Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    {
     "format": "bytes",
     "label": "1 Week Predicted Available Space"
    }
   ],
   "targets": [
    {
     "expr": "(sum by (job,cluster) (predict_linear(heketi_device_free_bytes [1d], 7 * 24 * 60 * 60) ))",
     "legendFormat": "{{job}} ({{cluster}})"
    }
   ]
  },
  {
   "title": "Heketi Status ($job)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "job",
   "collapsed": true,
   "panels": [
    {
     "title": "Heketi Status",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 4, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "heketi_up {job = \"$job\"}"
      }
     ]
    },
    {
     "title": "Available Capacity in a Week Based on Daily Use Rate",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 12, "y": 2 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum by (job,cluster) (predict_linear(heketi_device_free_bytes {job=\"$job\"}[1d], 7 * 24 * 60 * 60) ))"
      }
     ]
    },
    {
     "title": "Cluster Count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "heketi_cluster_count{job = \"$job\"}"
      }
     ]
    },
    {
     "title": "Volume Count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "heketi_volumes_count{job = \"$job\"}"
      }
     ]
    },
    {
     "title": "Block Volume Count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "heketi_block_volumes_count{job = \"$job\"}"
      }
     ]
    },
    {
     "title": "Total Size",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (heketi_device_size_bytes{job = \"$job\"})"
      }
     ]
    },
    {
     "title": "Used Space",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (heketi_device_used_bytes{job = \"$job\"})"
      }
     ]
    },
    {
     "title": "Free Space",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (heketi_device_free_bytes{job = \"$job\"})"
      }
     ]
    },
    {
     "title": "Available Capacity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes", "label": "Free Space" }
     ],
     "targets": [
      {
       "expr": "(\n  (sum by (job,cluster) (heketi_device_free_bytes {job = \"$job\"}))\n)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Available Capacity in a Week Based on Daily Use Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      {
       "format": "bytes",
       "label": "1 Week Predicted Available Space"
      }
     ],
     "targets": [
      {
       "expr": "(sum by (job,cluster) (predict_linear(heketi_device_free_bytes {job=\"$job\"} [1d], 7 * 24 * 60 * 60) ))",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Cluster Free Space by Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes", "label": "Free Space" }
     ],
     "targets": [
      {
       "expr": "(sum by (hostname) ( heketi_device_free_bytes {job = \"$job\"} ))",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Cluster Used Space by Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bytes", "label": "Free Space" }
     ],
     "targets": [
      {
       "expr": "(sum by (hostname) ( heketi_device_used_bytes {job = \"$job\"} ))",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Storage Devices Capacity Used",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "(sum by (hostname) ( heketi_device_used_bytes {job = \"$job\"} )) / (sum by (hostname) ( heketi_device_size_bytes {job = \"$job\"} ))",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Storage Device Useage",
     "type": "bargauge",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "(sum by (hostname, device) ( heketi_device_used_bytes {job = \"$job\"} )) / (sum by (hostname, device) ( heketi_device_size_bytes {job = \"$job\"} ))",
       "legendFormat": "{{hostname}} ({{device}})"
      }
     ]
    }
   ]
  }
 ]
}